### ISSUE TITLE
[Question] how to setup ray[tune] cluster?

### ISSUE THREAD

**Issue by mokhtarabadi** [enarjord/passivbot#122]
I'm not very familiar with python and ray[tune] but I understand I can make a cluster of multiple nodes for that, how I can do it?

**Comment by mokhtarabadi** [comment]
I try many ways, but i always see this error!

```Failure # 1 (occurred at 2021-05-26_14-05-41)
Traceback (most recent call last):
  File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train_buffered()[39m (pid=390292, ip=192.168.1.12)
  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.


```

**Comment by morteza-taheri** [comment]
> I try many ways, but i always see this error!
> 
> ```
> Traceback (most recent call last):
>   File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
>     results = self.trial_executor.fetch_result(trial)
>   File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
>     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
>   File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "pyenv/versions/3.8.5/envs/ray/lib/python3.8/site-packages/ray/worker.py", line 1456, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(RuntimeError): �[36mray::ImplicitFunc.train_buffered()�[39m (pid=390292, ip=192.168.1.12)
>   File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
> RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.
> ```
Are you using these two default configuration files?
configs\optimize\default.hjson
configs\backtest\default.hjson

If yes, just run optimize.py file and wait for the process to finish.

**Comment by mokhtarabadi** [comment]
Hey @morteza-taheri,
no, I changed the configs to my needs, but when running in single mode (local machine) everything works.
but optimize didn't work in the pre-created ray cluster, for this, I change `ray.init` to 
```python
ray.init(logging_level=logging.FATAL, log_to_driver=False, address='auto', _redis_password='password')
```

**Comment by morteza-taheri** [comment]
> Hey @morteza-taheri,
> no, I changed the configs to my needs, but when running in single mode (local machine) everything works.
> but optimize didn't work in the pre-created ray cluster, for this, I change `ray.init` to
> 
> ```python
> ray.init(logging_level=logging.FATAL, log_to_driver=False, address='auto', _redis_password='password')
> ```

Hi, by default, u don't need to change the parameters to use it in local mode, but try use
ray.init(num_cpus=num_cpus, logging_level=logging.FATAL, log_to_driver=False, local_mode=True)






and u can also try to change the number of CPUs and GPUs in this way

analysis = tune.run(
        backtest_wrap, metric='objective', mode='max', name='search',
        search_alg=algo, scheduler=scheduler, num_samples=iters, config=config, verbose=1,
        reuse_actors=True, local_dir=backtest_config['optimize_dirpath'],
        progress_reporter=LogReporter(metric_columns=['daily_gain',
                                                      'closest_liquidation',
                                                      'max_hrs_no_fills',
                                                      'max_hrs_no_fills_same_side',
                                                      'objective'],
                                      parameter_columns=[k for k in backtest_config['ranges']
                                                         if type(config[k]) == ray.tune.sample.Float
                                                         or type(config[k]) == ray.tune.sample.Integer]),
        raise_on_failed_trial=False,
        resources_per_trial={"cpu": 8, "gpu": 1}
    )

**Comment by mokhtarabadi** [comment]
I can't fix it, the problem is running paasivbot on the ray cluster (multiple
machines) instead, one machine, if it, not possibly close the issue

**Comment by mokhtarabadi** [comment]
@hoeckxer , I close it, I hope this will implement in the future
