### ISSUE TITLE
UnboundLocalError: local variable 'new_long_psize' referenced before assignment

### ISSUE THREAD

**Issue by jeet2k123** [enarjord/passivbot#124]
Getting this error on the latest master v3.5.3

fetching ticks... 11977 of 12711
debug len ticks, prices deque, ema_span
12901 12711 12711
The lock file has been removed succesfully
Task exception was never retrieved
future: <Task finished name='Task-51' coro=<Bot.decide() done, defined at /opt/passivbot/passivbot.py:416> exception=UnboundLocalError("local variable 'new_long_psize' referenced before assignment")>
Traceback (most recent call last):
  File "/opt/passivbot/passivbot.py", line 433, in decide
    await self.cancel_and_create()
  File "/opt/passivbot/passivbot.py", line 400, in cancel_and_create
    self.calc_orders(),
  File "/opt/passivbot/passivbot.py", line 341, in calc_orders
    for tpl in iter_entries(balance, long_psize, long_pprice, shrt_psize, shrt_pprice,
  File "/opt/passivbot/jitted.py", line 341, in iter_entries
    bankruptcy_price = calc_bankruptcy_price(balance, new_long_psize, new_long_pprice,
UnboundLocalError: local variable 'new_long_psize' referenced before assignment

**Comment by enarjord** [comment]
fixed in commit https://github.com/enarjord/passivbot/commit/b5c6723269dfa89b3e5adc67d9c6efcb048e6c4e

thx for reporting

**Comment by jeet2k123** [comment]
Works now...Thanks for quick fix
