### ISSUE TITLE
[Error] After run optimize.py

### ISSUE THREAD

**Issue by aumanusorn** [enarjord/passivbot#147]
2021-06-10T00:22:03  Saving single file with 347520972  ticks to backtests\binance\ETHUSDT\caches\2020-01-01T000000_2021-06-09T000000_ticks_cache.npy ... 
2021-06-10T00:22:21  Saved single file!

simple sliding window optimization

Traceback (most recent call last):
  File "optimize.py", line 264, in <module>
    asyncio.run(main())
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "optimize.py", line 258, in main
    analysis = backtest_tune(ticks, config)
  File "optimize.py", line 191, in backtest_tune
    backtest_wrap = tune.with_parameters(simple_sliding_window_wrap, ticks=ticks)
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\function_runner.py", line 628, in with_parameters
    parameter_registry.put(prefix + k, v)
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\registry.py", line 162, in put
    self.flush()
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\registry.py", line 171, in flush
    self.references[k] = ray.put(v)
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\worker.py", line 1489, in put
    object_ref = worker.put_object(value)
  File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\worker.py", line 277, in put_object
    self.core_worker.put_serialized_object(
  File "python\ray\_raylet.pyx", line 994, in ray._raylet.CoreWorker.put_serialized_object
  File "python\ray\_raylet.pyx", line 918, in ray._raylet.CoreWorker._create_put_buffer
  File "python\ray\_raylet.pyx", line 145, in ray._raylet.check_status
ray.exceptions.ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff0100000001000000 in object store because it is full. Object size is 8340503586 bytes.
The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.

**Comment by morteza-taheri** [comment]
> 2021-06-10T00:22:03 Saving single file with 347520972 ticks to backtests\binance\ETHUSDT\caches\2020-01-01T000000_2021-06-09T000000_ticks_cache.npy ...
> 2021-06-10T00:22:21 Saved single file!
> 
> simple sliding window optimization
> 
> Traceback (most recent call last):
> File "optimize.py", line 264, in
> asyncio.run(main())
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\asyncio\runners.py", line 44, in run
> return loop.run_until_complete(main)
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\asyncio\base_events.py", line 616, in run_until_complete
> return future.result()
> File "optimize.py", line 258, in main
> analysis = backtest_tune(ticks, config)
> File "optimize.py", line 191, in backtest_tune
> backtest_wrap = tune.with_parameters(simple_sliding_window_wrap, ticks=ticks)
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\function_runner.py", line 628, in with_parameters
> parameter_registry.put(prefix + k, v)
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\registry.py", line 162, in put
> self.flush()
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\registry.py", line 171, in flush
> self.references[k] = ray.put(v)
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray_private\client_mode_hook.py", line 47, in wrapper
> return func(*args, **kwargs)
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\worker.py", line 1489, in put
> object_ref = worker.put_object(value)
> File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\worker.py", line 277, in put_object
> self.core_worker.put_serialized_object(
> File "python\ray_raylet.pyx", line 994, in ray._raylet.CoreWorker.put_serialized_object
> File "python\ray_raylet.pyx", line 918, in ray._raylet.CoreWorker._create_put_buffer
> File "python\ray_raylet.pyx", line 145, in ray._raylet.check_status
> ray.exceptions.ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff0100000001000000 in object store because it is full. Object size is 8340503586 bytes.
> The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.

Hi, 
How much RAM does your system have? I think the system you are using is weak.

**Comment by eliafino** [comment]
Reduce days, range too wide! And too little RAM

**Comment by aumanusorn** [comment]
> > 2021-06-10T00:22:03 Saving single file with 347520972 ticks to backtests\binance\ETHUSDT\caches\2020-01-01T000000_2021-06-09T000000_ticks_cache.npy ...
> > 2021-06-10T00:22:21 Saved single file!
> > simple sliding window optimization
> > Traceback (most recent call last):
> > File "optimize.py", line 264, in
> > asyncio.run(main())
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\asyncio\runners.py", line 44, in run
> > return loop.run_until_complete(main)
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\asyncio\base_events.py", line 616, in run_until_complete
> > return future.result()
> > File "optimize.py", line 258, in main
> > analysis = backtest_tune(ticks, config)
> > File "optimize.py", line 191, in backtest_tune
> > backtest_wrap = tune.with_parameters(simple_sliding_window_wrap, ticks=ticks)
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\function_runner.py", line 628, in with_parameters
> > parameter_registry.put(prefix + k, v)
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\registry.py", line 162, in put
> > self.flush()
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\tune\registry.py", line 171, in flush
> > self.references[k] = ray.put(v)
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray_private\client_mode_hook.py", line 47, in wrapper
> > return func(*args, **kwargs)
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\worker.py", line 1489, in put
> > object_ref = worker.put_object(value)
> > File "C:\Users\anusorbo\Anaconda3\envs\tradebot\lib\site-packages\ray\worker.py", line 277, in put_object
> > self.core_worker.put_serialized_object(
> > File "python\ray_raylet.pyx", line 994, in ray._raylet.CoreWorker.put_serialized_object
> > File "python\ray_raylet.pyx", line 918, in ray._raylet.CoreWorker._create_put_buffer
> > File "python\ray_raylet.pyx", line 145, in ray._raylet.check_status
> > ray.exceptions.ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff0100000001000000 in object store because it is full. Object size is 8340503586 bytes.
> > The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.
> 
> Hi,
> How much RAM does your system have? I think the system you are using is weak.

32 GB
