### ISSUE TITLE
error when trying to load settings

### ISSUE THREAD

**Issue by thiazzz** [enarjord/passivbot#19]
see screenshot. What can I do?

<img width="826" alt="Screenshot 2021-02-16 at 18 54 38" src="https://user-images.githubusercontent.com/11335909/108102202-87bb6300-7088-11eb-9c1a-e70cf8a8c23f.png">

**Comment by jalanga** [comment]
I think is from python version, := was introduced in python ~3.8.1

**Comment by JohnKearney1** [comment]
Make sure your python is updated to python 3.8 or above, I'm using 3.9.1. 
Latest version of python is here: https://www.python.org/downloads/

Make sure your api keyfile is formatted correctly:
'["EXAMPLE_KEY", "EXAMPLE_SECRET"]'

Make sure you are using the correct python version, something environment pathing can force the wrong version to be used. If on linux, try with the 'sudo' prefix, or run as administrator from windows, and make sure you use 'python3' not 'python'.

**Comment by thiazzz** [comment]
I tried a lot with python 3.9 and 3.8 but still get this error. the json file with keys is ok.
I even get the error with the default key file.

<img width="826" alt="Screenshot 2021-02-16 at 18 54 38" src="https://user-images.githubusercontent.com/11335909/108123184-c0b60080-70a5-11eb-85fe-4fffcabc6ab4.png">

**Comment by JohnKearney1** [comment]
I'm not able to replicate the error. Confirm you're using the latest version (1.1.1) and have the dependencies installed as per the readme. I'm inclined to think it's something to do with python itself but I'm not quite sure what... 

to confirm, you're running; 'python3 start_bot.py binance username' correct?
You might try with 'python' if so. 

Line 173 retrieves the api keys for the bot based on what exchange is selected. I'm unsure why the error is on the ':=' as it's just a short variable declaration for 'ks'.

**Comment by enarjord** [comment]
I've seen reports of that error many times and the cause has always been too old python version.

what's the output of the command
`python3 --version`?

**Comment by thiazzz** [comment]
okay got it running, thanks for your help!
