### ISSUE TITLE
bot reports error

### ISSUE THREAD

**Issue by vantanphuoc** [enarjord/passivbot#237]
Starting binance_01 TXZUSDT configs/live/binance_xtzustd.json futures
Traceback (most recent call last):
  File "passivbot.py", line 11, in <module>
    from procedures import load_live_config, make_get_filepath, load_exchange_key_secret, print_, add_argparse_args
  File "/root/passivbot/procedures.py", line 4, in <module>
    import hjson
ModuleNotFoundError: No module named 'hjson'
bot stopped, attempting restart in 0 seconds

Please help me. Thank!

**Comment by rayures** [comment]
used the search and tried this? #228

**Comment by vantanphuoc** [comment]
Thank you, I have successfully fixed the error. bot is running.
