### ISSUE TITLE
okx - Leverage

### ISSUE THREAD

**Issue by ilaykim** [enarjord/passivbot#371]
in okx in order to change leverage, you need to cancel all orders first. then change leverage. 
I was only able to do it manually (cancelling all orders then changing leverage)

I couldn't get passivbot to change leverage even if I forced all open orders to cancel.

```
okx {"code":"59107","data":[],"msg":"Leverage can't be modified. Please cancel all pending cross margin orders before adjusting the leverage."}
```

**Comment by enarjord** [comment]
passivbot changing okx leverage worked for me if i manually cancelled all orders first

i think it's better to leave it up to the user to deal with this, rather than having passivbot check current leverage, and if it needs to change, cancel all orders, then change leverage

**Comment by ilaykim** [comment]
super!
I might have done something wrong testing.
will test again.
