### ISSUE TITLE
Manager issue 

### ISSUE THREAD

**Issue by Glaverd** [enarjord/passivbot#391]
I do not know why, I configured everything according to the instructions, but my manager does not launch the bot
![x5VQgp12ybQ~2](https://user-images.githubusercontent.com/121048879/230302788-c3300ee2-5640-4869-9e23-b37642082536.jpg)

**Comment by Sarmerer** [comment]
What does the log file for any symbol say?

**Comment by Glaverd** [comment]
> What does the log file for any symbol say?

Log folder is empty

**Comment by Glaverd** [comment]
> > What does the log file for any symbol say?
> 
> Log folder is empty

Just user folder, but user folder is empty

**Comment by Glaverd** [comment]
I wrote the wrong api path
