### ISSUE TITLE
Binance error -5022

### ISSUE THREAD

**Issue by djdeathdj** [enarjord/passivbot#437]
Errors like this appear from time to time

File "/home/clore/bot/passivbot/exchanges/binance.py", line 450, in <listcomp>
return [
File "/home/clore/bot/passivbot/exchanges/binance.py", line 447, in execute_batch_orders
Traceback (most recent call last):

returned: [{'code': -5022, 'msg': 'Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history'}, {'orderId': 1405234856, 'symbol': 'PHBUSDT', 'status': 'NEW', 'clientOrderId': 'shrtnclsa772eeb9868c4dc98a43aab8fa64', 'price': '1.1240000', 'avgPrice': '0.00', 'origQty': '22', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0.0000000', 'timeInForce': 'GTX', 'type': 'LIMIT', 'reduceOnly': True, 'closePosition': False, 'side': 'BUY', 'positionSide': 'SHORT', 'stopPrice': '0.0000000', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'LIMIT', 'priceMatch': 'NONE', 'selfTradePreventionMode': 'NONE', 'goodTillDate': 0, 'updateTime': 1709419134696}]

returned: {'orderId': 1405234856, 'symbol': 'PHBUSDT', 'status': 'NEW', 'clientOrderId': 'shrtnclsa772eeb9868c4dc98a43aab8fa64', 'price': '1.1240000', 'avgPrice': '0.00', 'origQty': '22', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0.0000000', 'timeInForce': 'GTX', 'type': 'LIMIT', 'reduceOnly': True, 'closePosition': False, 'side': 'BUY', 'positionSide': 'SHORT', 'stopPrice': '0.0000000', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'LIMIT', 'priceMatch': 'NONE', 'selfTradePreventionMode': 'NONE', 'goodTillDate': 0, 'updateTime': 1709419134696}

returned: {'code': -5022, 'msg': 'Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history'}

error executing order [{'code': -5022, 'msg': 'Due to the order could not be executed as maker, the Post Only order will be rejected. The order will not be recorded in the order history'}, 

{'orderId': 1405234856, 'symbol': 'PHBUSDT', 'status': 'NEW', 'clientOrderId': 'shrtnclsa772eeb9868c4dc98a43aab8fa64', 'price': '1.1240000', 'avgPrice': '0.00', 'origQty': '22', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0.0000000', 'timeInForce': 'GTX', 'type': 'LIMIT', 'reduceOnly': True, 'closePosition': False, 'side': 'BUY', 'positionSide': 'SHORT', 'stopPrice': '0.0000000', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'LIMIT', 'priceMatch': 'NONE', 'selfTradePreventionMode': 'NONE', 'goodTillDate': 0, 'updateTime': 1709419134696}] 'side'

**Comment by enarjord** [comment]
No harm in it. It tries to make a post-only order, but the order book changed, so it is rejected. It will try again next cycle with an updated order book.
