### ISSUE TITLE
Bybit fee

### ISSUE THREAD

**Issue by JohnyX** [enarjord/passivbot#452]
Is the commission calculated correctly? I set the maker_fee=0.0360 and taker_fee=0.1 for Bybit because the Bybit website lists the taker fee as 0.1% and the maker fee as 0.036%. However, the backtest on XLMUSDT shows a Fee sum of -16.7 from an initial deposit of 100 over 14 days and 48 trades, which seems implausibly high.

**Comment by enarjord** [comment]
The convention in Passivbot's code is to use decimals or ratios (per uno), not percent. So to express 1%, put 0.01 and 0.3%, put 0.003.

The numbers you put were 10% taker fee and 3.6% maker fee. Try instead maker_fee=0.000360 and taker_fee=0.001.

**Comment by JohnyX** [comment]
Despite the fees indicated on the website, in practice, I found exactly the coefficients specified in the code
