### ISSUE TITLE
Artifacts in forager optimizer output

### ISSUE THREAD

**Issue by hotstone228** [enarjord/passivbot#461]
V7.0.0

during optimization in 10+ threads, truncated lines appear in the final `*_opt_results.txt` file, which makes it impossible to use `extract_best_config_forager.py`

Perhaps this occurs due to inconsistency between threads when writing to a file.
I think you can either change the mechanism for writing to a file, or let each thread write to its own file, and then combine it into one, or write everything at once at the end of optimization.

beginning of lines:
![image](https://github.com/user-attachments/assets/124e93a6-c61f-41bb-b126-4b12fda63f14)

end of lines:
![image](https://github.com/user-attachments/assets/8d9ef973-8b0f-478d-a673-e9efb81f6bea)

optimization log: 
[optimize.log](https://github.com/user-attachments/files/16530924/optimize.log)

**Comment by LeonSpors** [comment]
Use this script to prepare the results file by removing any invalid lines.

Usage: **python ./prepare_result_set.py < file path >**

```python
import json
import sys

def process_file(file_path):
    try:
        # Read all lines from the file
        with open(file_path, 'r') as file:
            lines = file.readlines()

        correct_lines = []
        lines_removed = 0

        # Iterate over the lines in reverse order
        for line in reversed(lines):
            line = line.strip()
            passed = False

            try:
                # Try to deserialize the line into a JSON object
                json.loads(line)
                passed = True
            except json.JSONDecodeError:
                lines_removed += 1
                passed = False

            if passed:
                correct_lines.append(line)

        # Write the valid lines back to the file in the original order
        if lines_removed > 0:
            with open(file_path, 'w') as file:
                for cline in reversed(correct_lines):  # Reverse it back to original order
                    file.write(cline + '\n')

        print(f"{lines_removed} invalid lines removed")
    
    except Exception as e:
        print(f"An error occurred while processing the file: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python script.py <file_path>")
    else:
        file_path = sys.argv[1]
        process_file(file_path)
```

**Comment by hotstone228** [comment]
It seems that the latest version of optimize.py writes to the file correctly
