### ISSUE TITLE
Forager Script Ignores Minimum Order Value When Using "-lc" Flag

### ISSUE THREAD

**Issue by protoad56** [enarjord/passivbot#471]
Issue Summary:
When using the -lc flag in the coin_flags configuration, the forager script fails to check for the minimum order value. This oversight results in the repeated error message "Order must have minimum value" on the Hyperliquid exchange.

Steps to Reproduce:
1. Configure the forager script with the -lc flag in the coin_flags settings.
2. Run the forager script connected to the Hyperliquid exchange.
3. Observe that the script attempts to place orders without considering the exchange's minimum order value.
Note the repeated error messages: "Order must have minimum value."

Expected Behavior:
The forager script should verify the exchange's minimum order value when the -lc flag is used and prevent the submission of orders that do not meet this requirement.

Actual Behavior:
The script submits orders without checking the minimum cost.
The Hyperliquid exchange rejects these orders, displaying the error message "Order must have minimum value" repeatedly.

Additional Information:
Exchange: Hyperliquid
Attachment: Error message and configuration file

Possible Cause:
The logic for validating the minimum order value may be bypassed or not implemented when the -lc flag is active.

Suggested Fix:
Implement a check within the forager script to ensure that all orders meet the minimum value requirement of the exchange when the -lc flag is used.

[config-all-coins.json](https://github.com/user-attachments/files/17213284/config-all-coins.json)
<img width="1200" alt="Screenshot 2567-10-01 at 17 41 55" src="https://github.com/user-attachments/assets/26021a10-8618-4b24-b706-ceb4a4f5422e">

**Comment by enarjord** [comment]
Which passivbot version? And what was the symbol, qty and price of the order which failed? (It should have been printed above the traceback in the screenshot)

**Comment by protoad56** [comment]
I use the latest commit (feb6554ef54781869c5e144be283782d2846afeb)
attached the screenshot for symbol, qty and price
<img width="1223" alt="Screenshot 2567-10-03 at 09 19 32" src="https://github.com/user-attachments/assets/311a824e-c9ec-4d48-ab56-d412a9b19b94">

**Comment by protoad56** [comment]
after apply 6cdfbafcef4e7ff72f2fc6a6584bf3eb53fea943 I do not observe this error anymore. Thanks a lot ~!
